---
- name: Testing andrewrothstein.flux
  hosts: all
  tasks:
    - name: Installing andrewrothstein.flux
      ansible.builtin.include_role:
        name: '{{ playbook_dir }}'
    - name: Executing 'flux --version'
      ansible.builtin.command: /usr/local/bin/flux --version
      changed_when: false
      register: flux_test_output
    - name: Output of 'flux --version'
      ansible.builtin.debug:
        msg: '{{ flux_test_output.stdout }}'
