---
- hosts: all
  roles:
  - role: '{{ playbook_dir }}'
  tasks:
  - command: /usr/local/bin/flux --version
    register: flux_test_output
  - name: flux --version
    debug:
      msg: '{{ flux_test_output.stdout }}'
