---
- include_role:
    name: andrewrothstein.unarchive-deps
- name: resolve platform specific vars
  include_vars: '{{ item }}'
  with_first_found:
    - files:
        - '{{ ansible_distribution }}-{{ ansible_distribution_release }}.yml'
        - '{{ ansible_distribution }}.yml'
        - '{{ ansible_os_family }}.yml'
      skip: true
      paths:
        - '{{ role_path }}/vars'
- name: check for install in {{ flux_install_dir }}
  become: true
  stat:
    path: '{{ flux_install_dir }}'
  changed_when: false
  register: flux_binary
- when: not flux_binary.stat.exists
  block:
    - name: downloading {{ flux_url }} to {{ flux_tmp_archive }}
      become: true
      become_user: root
      get_url:
        url: '{{ flux_url }}'
        dest: '{{ flux_tmp_archive }}'
        checksum: '{{ flux_checksum }}'
        mode: 0644
    - name: mkdir {{ flux_install_dir }}
      become: true
      become_user: root
      file:
        path: '{{ flux_install_dir }}'
        state: directory
        mode: 0755
    - name: unarchiving {{ flux_tmp_archive }} to {{ flux_install_dir }}
      become: true
      become_user: root
      unarchive:
        remote_src: true
        src: '{{ flux_tmp_archive }}'
        dest: '{{ flux_install_dir }}'
        creates: '{{ flux_install_exe }}'
  always:
    - name: rm {{ flux_tmp_archive }}
      become: true
      become_user: root
      file:
        path: '{{ flux_tmp_archive }}'
        state: absent
- name: linking {{ flux_install_link }} to {{ flux_install_exe }}
  become: true
  become_user: root
  file:
    src: '{{ flux_install_exe }}'
    dest: '{{ flux_install_link }}'
    state: link
